story6/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6App.urls'))
]

story6App/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'story6App'

urlpatterns = [
    path('', views.index, name='index'),
    path('tambahStatus/', views.tambahStatus, name='tambahStatus'),
]

story6App/models.py
from django.db import models

# Create your models here.

class Status(models.Model):
    status = models.CharField(max_length=300)
    waktuInput = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.status    

story6App/forms.py
from django import forms


class formInput(forms.Form):
    status = forms.CharField(max_length=300, widget = forms.TextInput(
        attrs={'class' : 'form-control', 'placeholder' : 'Status', 'id' : 'status'}))

story6App/views.py
from django.shortcuts import render, redirect

from django.views.decorators.http import require_POST

from .forms import formInput
from .models import Status


# Create your views here.

def index(request):
    list_status = Status.objects.order_by('waktuInput')
    form = formInput()
    context = {'list_status' : list_status, 'form' : form}
    return render(request, 'landingPage.html', context)

@require_POST
def tambahStatus(request):
    form = formInput(request.POST)

    statusBaru = Status(status = request.POST['status'])

    # statusBaru = Status(statusMasuk = request.POST['inputStatus'])
    statusBaru.save()
    
    return redirect('story6App:index')

story6App/templates/landingPage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Landing Page</title>
</head>
<body>
    <h1>Halo, apa kabar?</h1>
    <div class="form-group">
        <label>Input status</label>
        <form method="POST" action="{% url 'story6App:tambahStatus' %}" required>
                {% csrf_token %}
                {{ form.status }}
                <button type="submit" class="" id="submit">Submit</button>
        </form>
        
    </div>
    {% for i in list_status %}
        <p>{{ i.status }} || {{ i.waktuInput }}</p>
    {% endfor %}

</body>
</html>